const tzi = require('./tzi')

let wr = new tzi(1)
console.log("name: ", wr.name)
console.log("natural: ", wr.natural)
console.log("seniority: ", wr.seniority)
console.log("order: ", wr.order)
console.log("elementOrder: ", wr.elementOrder)
console.log("opposite: ", wr.opposite)
console.log("duo: ", wr.duo)
console.log("trine(5): ", wr.trine(5))
console.log("square(4): ", wr.square(4))
let fr = new tzi(4)
console.log("name: ", fr.name)
console.log("natural: ", fr.natural)
console.log("seniority: ", fr.seniority)
console.log("order: ", fr.order)
console.log("elementOrder: ", fr.elementOrder)
console.log("opposite: ", fr.opposite)
console.log("duo: ", fr.duo)
console.log("trine(5): ", fr.trine(5))
console.log("square(4): ", fr.square(4))
let wm = new tzi(9)
console.log("name: ", wm.name)
console.log("natural: ", wm.natural)
console.log("seniority: ", wm.seniority)
console.log("order: ", wm.order)
console.log("elementOrder: ", wm.elementOrder)
console.log("opposite: ", wm.opposite)
console.log("duo: ", wm.duo)
console.log("trine(5): ", wm.trine(5))
console.log("square(4): ", wm.square(4))
let mr = new tzi(28)
console.log("name: ", mr.name)
console.log("natural: ", mr.natural)
console.log("seniority: ", mr.seniority)
console.log("order: ", mr.order)
console.log("elementOrder: ", mr.elementOrder)
console.log("opposite: ", mr.opposite)
console.log("duo: ", mr.duo)
console.log("trine(5): ", mr.trine(5))
console.log("square(4): ", mr.square(4))
console.log("kind(4): ", mr.kind(4))
console.log("kind(31): ", mr.kind(31))
console.log("diversityTrine(56, 12): ", mr.diversityTrine(56, 12))
console.log("diversitySquare(1, 10, 55): ", mr.diversityTrine(1, 10, 55))
console.log(tzi.elements)
console.log(tzi.animals)

