const Tzi = require('./tzi')


let woodRat = new Tzi(1)
console.log("name: ", woodRat.name)
console.log("natural: ", woodRat.natural)
console.log("seniority: ", woodRat.seniority)
console.log("order: ", woodRat.order)
console.log("elementOrder: ", woodRat.elementOrder)
console.log("opposite: ", woodRat.opposite)
console.log("duo: ", woodRat.duo)
console.log("trine(5): ", woodRat.trine(5))
console.log("square(4): ", woodRat.square(4))
let fireRabbit = new Tzi(4)
console.log("name: ", fireRabbit.name)
console.log("polarity: ", fireRabbit.polarity)
console.log("natural: ", fireRabbit.natural)
console.log("seniority: ", fireRabbit.seniority)
console.log("order: ", fireRabbit.order)
console.log("elementOrder: ", fireRabbit.elementOrder)
console.log("opposite: ", fireRabbit.opposite)
console.log("duo: ", fireRabbit.duo)
console.log("trine(5): ", fireRabbit.trine(5))
console.log("square(4): ", fireRabbit.square(4))
let waterMonkey = new Tzi(9)
console.log("name: ", waterMonkey.name)
console.log("polarity: ", waterMonkey.polarity)
console.log("natural: ", waterMonkey.natural)
console.log("seniority: ", waterMonkey.seniority)
console.log("order: ", waterMonkey.order)
console.log("elementOrder: ", waterMonkey.elementOrder)
console.log("opposite: ", waterMonkey.opposite)
console.log("duo: ", waterMonkey.duo)
console.log("trine(5): ", waterMonkey.trine(5))
console.log("square(4): ", waterMonkey.square(4))
let metalRabbit = new Tzi(28)
console.log("name: ", metalRabbit.name)
console.log("natural: ", metalRabbit.natural)
console.log("seniority: ", metalRabbit.seniority)
console.log("order: ", metalRabbit.order)
console.log("elementOrder: ", metalRabbit.elementOrder)
console.log("opposite: ", metalRabbit.opposite)
console.log("duo: ", metalRabbit.duo)
console.log("trine(5): ", metalRabbit.trine(5))
console.log("square(4): ", metalRabbit.square(4))
console.log("kind(4): ", metalRabbit.kind(4))
console.log("kind(31): ", metalRabbit.kind(31))
console.log("diversityTrine(56, 12): ", metalRabbit.diversityTrine(56, 12))
console.log("diversitySquare(1, 10, 55): ", metalRabbit.diversityTrine(1, 10, 55))
console.log("yin: ", metalRabbit.yin)
console.log("yang: ", metalRabbit.yang)
console.log(Tzi.elements)
console.log(Tzi.animals)
console.log(Tzi.range)

